/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU */

#ifndef _Included_br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU
#define _Included_br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU_init
  (JNIEnv *, jobject);

/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU
 * Method:    cleanUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU_cleanUp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU
 * Method:    nativeRunOp
 * Signature: (JII[BFFLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardOpenCLOperatorCPU_nativeRunOp
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
