/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator */

#ifndef _Included_br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator
#define _Included_br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator
 * Method:    init
 * Signature: (Landroid/content/Context;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator_init
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator
 * Method:    cleanUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator_cleanUp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator
 * Method:    nativeRunOp
 * Signature: (JII[BFFLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator_nativeRunOp
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray, jfloat, jfloat, jobject);

/*
 * Class:     br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator
 * Method:    nativeWaitFinish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_br_ufmg_dcc_tonemapreinhard_ReinhardScheduledOperator_nativeWaitFinish
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
