/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM */

#ifndef _Included_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
#define _Included_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
 * Method:    iterator1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM_iterator1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
 * Method:    iterator2
 * Signature: (JJF[FF[F)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM_iterator2
  (JNIEnv *, jobject, jlong, jlong, jfloat, jfloatArray, jfloat, jfloatArray);

/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
 * Method:    iterator3
 * Signature: (JJFF)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM_iterator3
  (JNIEnv *, jobject, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
 * Method:    iterator4
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM_iterator4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM
 * Method:    iterator5
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardCollectionOperatorWrapperImplPM_iterator5
  (JNIEnv *, jobject, jlong, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
