/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_parallelme_ParallelMERuntime */

#ifndef _Included_org_parallelme_ParallelMERuntime
#define _Included_org_parallelme_ParallelMERuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_parallelme_ParallelMERuntime
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_parallelme_ParallelMERuntime_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_parallelme_ParallelMERuntime
 * Method:    nativeCleanUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_ParallelMERuntime_nativeCleanUp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_parallelme_ParallelMERuntime
 * Method:    nativeCreateHDRImage
 * Signature: (J[BII)J
 */
JNIEXPORT jlong JNICALL Java_org_parallelme_ParallelMERuntime_nativeCreateHDRImage
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_parallelme_ParallelMERuntime
 * Method:    nativeToBitmapHDRImage
 * Signature: (JJLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_ParallelMERuntime_nativeToBitmapHDRImage
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     org_parallelme_ParallelMERuntime
 * Method:    nativeGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_parallelme_ParallelMERuntime_nativeGetHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_parallelme_ParallelMERuntime
 * Method:    nativeGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_parallelme_ParallelMERuntime_nativeGetWidth
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
