/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU */

#ifndef _Included_org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU
#define _Included_org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU_init
  (JNIEnv *, jobject);

/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU
 * Method:    cleanUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU_cleanUp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU
 * Method:    nativeRunOp
 * Signature: (JII[BFFLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_tonemapreinhard_ReinhardOpenCLOperatorGPU_nativeRunOp
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
