/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_parallelme_samples_grayscale_GrayscaleOperator */

#ifndef _Included_org_parallelme_samples_grayscale_GrayscaleOperator
#define _Included_org_parallelme_samples_grayscale_GrayscaleOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_parallelme_samples_grayscale_GrayscaleOperator
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_parallelme_samples_grayscale_GrayscaleOperator_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_parallelme_samples_grayscale_GrayscaleOperator
 * Method:    nativeCleanUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_grayscale_GrayscaleOperator_nativeCleanUp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_parallelme_samples_grayscale_GrayscaleOperator
 * Method:    nativeGrayscale
 * Signature: (JLandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_org_parallelme_samples_grayscale_GrayscaleOperator_nativeGrayscale
  (JNIEnv *, jobject, jlong, jobject, jint width, jint height);

#ifdef __cplusplus
}
#endif
#endif
